### ISSUE TITLE
Google colab notebook not working

### ISSUE THREAD

**Issue by anibaljasin** [Tony607/object_detection_demo#18]
Hi, I tried your google colab for object detection and in the training stage it raise this exception:

`INFO:tensorflow:Loading and preparing annotation results...
I0329 19:33:45.885196 140260674410240 coco_tools.py:115] Loading and preparing annotation results...
INFO:tensorflow:DONE (t=0.00s)
I0329 19:33:45.885412 140260674410240 coco_tools.py:137] DONE (t=0.00s)
creating index...
index created!
2020-03-29 19:33:45.894500: W tensorflow/core/framework/op_kernel.cc:1639] Invalid argument: TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)

TypeError: 'numpy.float64' object cannot be interpreted as an integer`

The only thing that I changed to the original notebook is that I used tensorflow 1.x because otherwise it won't work with the 2.x version.

Is this related to the tensorflow version you used? could you tell me which specific version you used? 

thanks.

**Comment by shivam1423** [comment]
After quite a bit of troubleshooting I found there is a change is numpy 1.18.0 which causes this. The fix is:

`!sudo -H pip3 install numpy==1.17.4`

A few things I can also mention:

-numpy 1.17.4 was released on November 10th, 2019 and therefore should still be good for quite some time

-There is now a pip package for pycocotools, so instead of the above procedure (cloning and building) you can now simply do:

`!sudo -H pip3 install pycocotools`

**Comment by anibaljasin** [comment]
okay thanks @shivam1423 !
